name: dominioncity-church
region: nyc
features:
  - buildpack-stack=ubuntu-22

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1

services:
  - name: server
    github:
      repo: Techtink/dominioncity-church
      branch: main
      deploy_on_push: true
    source_dir: server
    build_command: npm ci && npx prisma generate
    run_command: npx prisma db push --skip-generate && node src/index.js
    http_port: 5001
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    envs:
      - key: PORT
        value: "5001"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET

static_sites:
  - name: client
    github:
      repo: Techtink/dominioncity-church
      branch: main
      deploy_on_push: true
    source_dir: client
    build_command: npm ci && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        value: /api
    catchall_document: index.html

ingress:
  rules:
    - component:
        name: server
      match:
        path:
          prefix: /api
    - component:
        name: server
      match:
        path:
          prefix: /socket.io
    - component:
        name: server
      match:
        path:
          prefix: /uploads
    - component:
        name: client
      match:
        path:
          prefix: /
